// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
    "github.com/gogf/gf/os/gtime"
)


// Test1 is the golang structure for table test1.
type Test1 struct {
    Id int         `orm:"id,primary" json:"id"` //   
    Ct *gtime.Time `orm:"ct"         json:"ct"` //   
}


// Test2 is the golang structure for table test2.
type Test2 struct {
    Id int   `orm:"id,primary" json:"id"` //   
    Ct int64 `orm:"ct"         json:"ct"` //   
}


// Test3 is the golang structure for table test3.
type Test3 struct {
    Id int         `orm:"id,primary" json:"id"` //   
    Ct *gtime.Time `orm:"ct"         json:"ct"` //   
}