// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"study/app/dao/internal"
)

// test2Dao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type test2Dao struct {
	*internal.Test2Dao
}

var (
	// Test2 is globally public accessible object for table test2 operations.
	Test2 test2Dao
)

func init() {
	Test2 = test2Dao{
		internal.NewTest2Dao(),
	}
}

// Fill with you ideas below.