// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"study/app/dao/internal"
)

// test1Dao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type test1Dao struct {
	*internal.Test1Dao
}

var (
	// Test1 is globally public accessible object for table test1 operations.
	Test1 test1Dao
)

func init() {
	Test1 = test1Dao{
		internal.NewTest1Dao(),
	}
}

// Fill with you ideas below.