// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"study/app/dao/internal"
)

// test3Dao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type test3Dao struct {
	*internal.Test3Dao
}

var (
	// Test3 is globally public accessible object for table test3 operations.
	Test3 test3Dao
)

func init() {
	Test3 = test3Dao{
		internal.NewTest3Dao(),
	}
}

// Fill with you ideas below.