// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// Test3Dao is the manager for logic model data accessing and custom defined data operations functions management.
type Test3Dao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C       test3Columns // C is the short type for Columns, which contains all the column names of Table for convenient usage.	
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the underlying table name of the DAO.
}

// Test3Columns defines and stores column names for table test3.
type test3Columns struct {
	Id  string //   
    Ct  string //
}

// NewTest3Dao creates and returns a new DAO object for table data access.
func NewTest3Dao() *Test3Dao {
    columns := test3Columns{
		Id: "id",  
            Ct: "ct",
	}
	return &Test3Dao{
		C: 	   columns,
		M:     g.DB("default").Model("test3").Safe(),
		DB:    g.DB("default"),
		Table: "test3",
	}
}